import turtle
t = turtle.Turtle()
t.fillcolor('blue')
t.begin_fill()
t.circle(50)
t.end_fill()
t.fillcolor('yellow')
t.begin_fill()
t.circle(30)
t.end_fill()
t.fillcolor('pink')
t.begin_fill()
t.circle(20)
t.end_fill()
t.hideturtle()